dist: trusty
sudo: true
group: beta
language: python
python:
    - "3.4"
    - "3.5"
services:
    postgresql
addons:
    postgresql: "9.4"
    apt:
        sources:
            - sourceline: deb http://deb.nodesource.com/node_6.x trusty main
            - key_url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        packages:
            - nodejs
            - chromium-browser
            - chromium-chromedriver
env:
    global:
        - DJANGO_SETTINGS_MODULE="accountant.settings.ci"
    matrix:
        - REVERSE=
        - REVERSE=--reverse
install:
    - pip install -r requirements/ci.txt
    - npm install -g @angular/cli
    - cd ngApp; npm install; cd ..
before_script:
    - "export PATH=$PATH:/usr/lib/chromium-browser"
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
    - psql -c "CREATE DATABASE accountant_ci" -U postgres
script:
    - ./build-ng-app.sh
    - cd accountant; coverage run manage.py test $REVERSE -v2
    - cd ../ngApp; ng test --single-run --browser Chromium --code-coverage
after_success:
    - cd ..
    - bash <(curl -s https://codecov.io/bash) -f accountant/.coverage -f ngApp/coverage/lcov.info
