dist: trusty
sudo: false
group: beta
language: python
python:
    - "3.4"
    - "3.5"
services:
    postgresql
addons:
    postgresql: "9.4"
    apt:
        sources:
            - sourceline: deb http://deb.nodesource.com/node_6.x trusty main
            - key_url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        packages:
            - google-chrome-stable
            - nodejs
env:
    global:
        - DJANGO_SETTINGS_MODULE="accountant.settings.ci"
    matrix:
        - REVERSE=
        - REVERSE=--reverse
install:
    - pip install -r requirements/ci.txt
    - npm install -g @angular/cli@1.0.0-rc.1
    - cd ngApp; npm install; cd ..
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
    - psql -c "CREATE DATABASE accountant_ci" -U postgres
    - wget https://chromedriver.storage.googleapis.com/2.28/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - export PATH=$PATH:$(pwd)
script:
    - ./build-ng-app.sh
    - cd accountant
    - coverage run manage.py test $REVERSE -v2
after_success:
    - codecov
