dist: trusty
sudo: false
group: beta
language: python
python:
    - "3.4"
    - "3.5"
services:
    postgresql
addons:
    postgresql: "9.4"
    apt:
        packages:
            - google-chrome-stable
env:
    global:
        - DJANGO_SETTINGS_MODULE="accountant.settings.ci"
    matrix:
        - REVERSE=
        - REVERSE=--reverse
install:
    - pip install -r requirements/ci.txt
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
    - psql -c "CREATE DATABASE accountant_ci" -U postgres
    - wget https://chromedriver.storage.googleapis.com/2.28/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - export PATH=$PATH:$(pwd)
script:
    - cd accountant
    - coverage run manage.py test $REVERSE -v2
after_success:
    - codecov
