dist: trusty
sudo: false
group: beta
language: python
python:
    - "3.4"
    - "3.5"
services:
    postgresql
addons:
    postgresql: "9.4"
env:
    global:
        - DJANGO_SETTINGS_MODULE="accountant.settings.ci"
    matrix:
        - REVERSE=
        - REVERSE=--reverse
install:
    - pip install -r requirements/ci.txt
before_script:
    - psql -c "CREATE DATABASE accountant_ci" -U postgres
script:
    - cd accountant
    - coverage run -p manage.py test functional_tests -v2 $REVERSE
    - coverage run -p manage.py test core -v2 $REVERSE
    - coverage run -p manage.py test interface -v2 $REVERSE
after_success:
    - coverage combine
    - codecov
