dist: trusty
sudo: true
group: beta
language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
cache:
    directories:
        - ngApp/node_modules
        - $HOME/.nvm/versions/node/v7.4.0/lib/node_modules
        - $HOME/.cache/pip
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
services:
    postgresql
addons:
    postgresql: "9.4"
    apt:
        sources:
            - sourceline: deb http://deb.nodesource.com/node_6.x trusty main
            - key_url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        packages:
            - nodejs
            - chromium-browser
            - chromium-chromedriver
env:
    global:
        - DJANGO_SETTINGS_MODULE="accountant.settings.ci"
    matrix:
        - REVERSE=
        - REVERSE=--reverse
install:
    - pip install -r requirements/ci.txt
    - npm install -g @angular/cli
    - cd ngApp; npm install; cd ..
before_script:
    - "export PATH=$PATH:/usr/lib/chromium-browser"
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
    - psql -c "CREATE DATABASE accountant_ci" -U postgres
script:
    - ./build-ng-app.sh -prod
    - cd accountant
    - coverage run manage.py test core $REVERSE -v2
    - coverage run manage.py test functional_tests $REVERSE -v2
    - flake8
    - cd ../ngApp; ng test --single-run --browser Chromium --code-coverage
after_success:
    - bash <(curl -s https://codecov.io/bash) -cF angular
    - cd ../accountant
    - bash <(curl -s https://codecov.io/bash) -cF python
