dist: trusty
sudo: false
group: beta
language: python
python:
    - "3.4"
    - "3.5"
services:
    postgresql
addons:
    postgresql: "9.4"
env:
    global:
        - DJANGO_SETTINGS_MODULE="accountant.settings.ci"
    matrix:
        - REVERSE=
        - REVERSE=--reverse
        - SUITE=functional_tests
        - SUITE=core
        - SUITE=interface
install:
    - pip install -r requirements/ci.txt
before_script:
    - psql -c "CREATE DATABASE accountant_ci" -U postgres
script:
    - cd accountant
    - coverage run manage.py test $SUITE $REVERSE -v2
after_success:
    - codecov
