#%RAML 1.0

title: 18xx accountant
description: |
    A computer moderator to keep track of 18xx finances

types:
  game:
    type: object
    default-access: read+insert+update
    properties:
        cash: integer
  player:
    type: object
    default-access: read
    properties:
        game: game
  company:
    type: object
    default-access: read
    properties:
        game: game
  playershare:
    type: object
    default-access: read
    properties:
        game: game
  companyshare:
    type: object
    default-access: read
    properties:
        game: game
  logentry:
    type: object
    default-access: read
    properties:
        game: game

/game:
/player:
/company:
/playershare:
/companyshare:
/logentry:
