# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161219_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank_shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='ipo_shares',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='company',
            name='shares',
            field=models.IntegerField(default=10),
        ),
    ]
