# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161219_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shares', models.IntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Player')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='owners',
            field=models.ManyToManyField(related_name='shares', through='core.Share', to='core.Player'),
        ),
    ]
