# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161219_2038'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set([('game', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('game', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='share',
            unique_together=set([('player', 'company')]),
        ),
    ]
