# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20161219_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='bank_cash',
            new_name='cash',
        ),
    ]
