# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170109_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='shares',
            new_name='share_count',
        ),
    ]
