# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170110_0020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Share',
            new_name='PlayerShare',
        ),
        migrations.RemoveField(
            model_name='company',
            name='owners',
        ),
        migrations.AddField(
            model_name='company',
            name='player_owners',
            field=models.ManyToManyField(related_name='shares', through='core.PlayerShare', to='core.Player'),
        ),
    ]
