# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170112_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playershare',
            old_name='player',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='playershare',
            unique_together=set([('owner', 'company')]),
        ),
    ]
