# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170112_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyshare',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_set', to='core.Company'),
        ),
        migrations.AlterField(
            model_name='playershare',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_set', to='core.Player'),
        ),
    ]
