# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-09 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170210_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='core.Game')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
