# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-09 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_game_log_cursor'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
