# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-30 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_game_pool_shares_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ipo_shares_pay',
            field=models.BooleanField(default=False),
        ),
    ]
