# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-01 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_game_ipo_shares_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='treasury_shares_pay',
            field=models.BooleanField(default=True),
        ),
    ]
