# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20171029_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Company'),
        ),
    ]
