# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20171202_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='revenue',
        ),
    ]
