---
- hosts: all
  name: Install dependencies
  become: true
  tasks:
      - name: Install dependencies from package manager
        apt:
            update_cache: yes
            state: latest
            name: "{{ item }}"
        with_items:
            - python3
            - python3-pip
            - git
            - postgresql-9.4
            - postgresql-server-dev-9.4
            - gettext
      - name: Install dependencies from pip
        pip:
            name: virtualenv
            executable: pip3

- hosts: all
  name: Set up variables on remote machine
  tasks:
      - name: Create variables directory
        file:
            path: "{{ sitename }}"
            state: directory
      - name: Create variables file
        template:
            src: "deploy/variables.ini.j2"
            dest: "{{ sitename }}/variables.fact"

- hosts: all
  name: provisioning
  become: true
  fact_path: "~/{{ sitename }}"
  tasks:
      - name: Display facts
        shell: echo {{ database.name }}
      - name: Create log file directories
        file:
            path: /var/log/gunicorn
            owner: www-data
            group: www-data
            mode: 0744
            state: directory
      - name: Create directories too store application
        check_mode: yes
        file:
            path: /var/www/sites/{{ sitename }}/{{ item }}
            owner: www-data
            group: www-data
            mode: 0774
            state: directory
        with_items:
            - source
            - static
            - virtualenv
